spring:
  datasource:
    name: ds1
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: root
    password: root
    datasources:
      - name: ds2
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/testdb
        username: root
        password: root

logging:
  level:
    examples.mybatis: debug
    dynamicds: debug
